call plug#begin()

    Plug 'tpope/vim-fugitive'
    Plug 'ojroques/vim-oscyank', {'branch': 'main'}
	Plug 'preservim/nerdtree'
	Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && npx --yes yarn install' }

call plug#end()

set nocompatible

" Mainly about show effect
" Turn on syntax highlighting.
syntax on
" Disable the default Vim startup message.
set shortmess+=I
" Show line numbers.
set number
set relativenumber
" Show cmd in downline
set showcmd
" Do not soft wrap
set wrap
" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2
" highlight current line
set cursorline
" linebreak on special punctuation
set linebreak
" current cursor position
set noruler


" Mainly about indent
" file type check
filetype indent on
set autoindent
" Set tab to be 2 spaces
set noexpandtab
set tabstop=4 shiftwidth=4 softtabstop=4


" The backspace key has slightly unintuitive behavior by default. For example,
" by default, you can't backspace before the insertion point set with 'i'.
" This configuration makes backspace behave more reasonably, in that you can
" backspace over anything.
set backspace=indent,eol,start

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't
" shown in any window) that has unsaved changes. This is to prevent you from "
" forgetting about unsaved changes and then quitting e.g. via `:qa!`. We find
" hidden buffers helpful enough to disable this protection. See `:help hidden`
" for more information on this.
set hidden

" This setting makes search case-insensitive when all characters in the string
" being searched are lowercase. However, the search becomes case-sensitive if
" it contains any capital letters. This makes searching more convenient.
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Enable mouse support. You should avoid relying on this too much, but it can
" sometimes be convenient.
set mouse+=a

" Clipboard setting, add for GUI server with +clipboard
set clipboard=unnamed
" add for server with -clipboard
" nmap y <Plug>OSCYankOperator
" nmap yy y_
" vmap y <Plug>OSCYankVisual 

" prevent bad habits 
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
inoremap jj <ESC>l

" NERDTree keymapping
" ctrl + w + h/l	光标 focus 左侧/右侧
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR> 
" 让 NERDTree 在 Vim 启动时自动打开（如果没有文件）
autocmd VimEnter * if !argc() | NERDTree | endif
" 如果只剩下 NERDTree 窗口，自动退出 Vim
autocmd BufEnter * if winnr('$') == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree() | quit | endif
" 打开时刷新 NERDTree 状态（自动显示新建文件）
autocmd BufWritePost * NERDTreeRefreshRoot
" NERDTree 默认行为定制
let NERDTreeQuitOnOpen=1          " 打开文件后自动关闭树窗口
let NERDTreeShowHidden=1          " 显示隐藏文件（.开头）
let NERDTreeMinimalUI=1           " 精简 UI
let NERDTreeDirArrows=1           " 使用箭头符号指示目录

" Makedown-Preview
" normal/insert
nmap <C-s> <Plug>MarkdownPreview
nmap <M-s> <Plug>MarkdownPreviewStop
nmap <C-p> <Plug>MarkdownPreviewToggle
