# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-sidebar'
# xclip dependency, need to be installed
set -g @plugin 'tmux-plugins/tmux-yank'

# show effects
set-option -sa terminal-features ',xterm-256color:RGB'
set -g terminal-overrides "*88col*:colors=88,*256col*:colors=256,xterm*:colors=256"
set -g base-index 1
setw -g pane-base-index 1
# mouse setting
set -g mouse on
set-option -g set-titles on
# It rely on zsh to rename window title
setw -g automatic-rename off


# key binding
unbind-key C-b
unbind-key '"'
unbind-key %
set-option -g prefix `
bind-key ` send-prefix
bind-key \; command-prompt

setw -g mode-keys vi
setw -g xterm-keys off
bind-key - split-window -v
bind-key | split-window -h
bind-key h select-pane -L
bind-key l select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U

bind-key -n C-S-p swap-window -t -1\; select-window -t -1
bind-key -n C-S-n swap-window -t +1\; select-window -t +1

# plugin setting
set -g @continuum-restore 'on'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
# for vim
set -g @resurrect-strategy-vim 'session'
set -g @sidebar-tree-focus 'w'
set -g @sidebar-tree-pager 'view -'

# other setting
# scrollback buffer size increase
set -g history-limit 10000
set-option -g visual-activity on
setw -g monitor-activity on
# aliasing tmux to "tmux -2" should also do the trick
set -g status-justify centre
set -g status-style "bg=black,fg=white"
set -g status-left "#[fg=red][ #[fg=green]#h #[fg=red]]#[default]"
set -g status-left-length 20
set -g status-right-length 25
set -g status-right "#[fg=red][ #[fg=green]%H:%M #[fg=magenta]%a %m-%d #[fg=red]] #[default]"
#set -g message-style "fd=black,bg=colour109,bold"
setw -g window-status-format '#[fg=blue,bold]#I: #W#F#[default]'
setw -g window-status-current-format '#[fg=yellow,bold,reverse]#I: #W#F#[default] '
# add OSC52 setting 
set -s set-clipboard on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run-shell ~/.config/tmux/plugins/tmux-sensible/sensible.tmux
run-shell ~/.config/tmux/plugins/tmux-yank/yank.tmux
run-shell ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
# run-shell ~/.config/tmux/plugins/tmux-continuum/continuum.tmux
# run-shell ~/.config/tmux/plugins/tmux-sidebar/sidebar.tmux
run -b '~/.config/tmux/plugins/tpm/tpm'
