# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.config/zsh/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="crunch"

plugins=(
	git
	zsh-autosuggestions
	extract
	zsh-syntax-highlighting
	z
)


source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
fi

# General Configure
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5795ff,bg=gray,bold,underline"
alias ssh="TERM=xterm-256color ssh"

# Server Specfic Configure
# export PATH=~/venv/bin:$PATH


# Mac-os Specfic Configure
# export PATH=:/Users/bryan/venv/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:$GOROOT/bin:$JAVA_HOME/bin:$HDC_PATH:/usr/local/texlive/2025/bin/universal-darwin:/usr/local/nvim-macos-arm64/bin
# export HOMEBREW_NO_INSTALL_CLEANUP=TRUE


#Other config
# Setup fzf
unalias z
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source <(fzf --zsh) 
# Setup zoxide
eval "$(zoxide init zsh)"

# file modify
alias vi="nvim"
alias zr="nvim ~/.zshrc"

# app alias
alias cd="z "
alias tm="tmux"
alias tml="tmux ls"
alias tma="tmux attach"
alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias lg="lazygit"
alias python="python3"

# export http_proxy=http://ipads:ipads123@202.120.40.82:11235
# export https_proxy=http://ipads:ipads123@202.120.40.82:11235 
# export no_proxy=localhost,127.0.0.1
# export HF_ENDPOINT=https://hf-mirror.com


# Claude Code API Router configuration
export ANTHROPIC_BASE_URL="https://moacode.org"
export ANTHROPIC_AUTH_TOKEN="cr_d9bce7f539df5068853b95e82981628789f087f434c9e4857d9dc00656cddcd0"
