export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_CONFIG_ROOT="$ZDOTDIR"
export ZSH_MACHINE_NAME="${ZSH_MACHINE_NAME:-${HOST%%.*}}"

if [[ -z "$ZSH_MACHINE_NAME" ]]; then
  export ZSH_MACHINE_NAME="$(hostname -s 2>/dev/null || hostname 2>/dev/null)"
fi

_zsh_safe_source() {
  local file="$1"
  [[ -r "$file" ]] && source "$file"
}

_zsh_safe_source "$ZSH_CONFIG_ROOT/config/general.zsh"
_zsh_safe_source "$ZSH_CONFIG_ROOT/machines/$ZSH_MACHINE_NAME/public.zsh"
_zsh_safe_source "$ZSH_CONFIG_ROOT/machines/$ZSH_MACHINE_NAME/secret.zsh"

unset -f _zsh_safe_source
